//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmountRationInInvitation
    {
        public int CodeAmountRationInInvitation { get; set; }
        public int CodeRation { get; set; }
        public int AmountRationInvitation { get; set; }
    
        public virtual Rations Rations { get; set; }
    }
}
