//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invitations()
        {
            this.InvitationInTable = new HashSet<InvitationInTable>();
            this.RationInInvitation = new HashSet<RationInInvitation>();
        }
    
        public int CodeInvitation { get; set; }
        public Nullable<System.DateTime> DateInvitation { get; set; }
        public int CodeClient { get; set; }
        public decimal PriceToPay { get; set; }
        public string PaymentMethod { get; set; }
        public bool PaidOrUnpaid { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvitationInTable> InvitationInTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RationInInvitation> RationInInvitation { get; set; }
    }
}
