//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvitationInTable
    {
        public int CodeInvitationInTable { get; set; }
        public int CodeInvitation { get; set; }
        public int CodeTable { get; set; }
        public System.DateTime OrderHour { get; set; }
        public bool StatusTable { get; set; }
    
        public virtual Invitations Invitations { get; set; }
        public virtual Tables Tables { get; set; }
    }
}
