//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rations()
        {
            this.AmountRationInInvitation = new HashSet<AmountRationInInvitation>();
            this.RateRations = new HashSet<RateRations>();
            this.RationInInvitation = new HashSet<RationInInvitation>();
        }
    
        public int CodeRation { get; set; }
        public string NameRation { get; set; }
        public decimal PriceRation { get; set; }
        public int CodeCategory { get; set; }
        public string ContainRation { get; set; }
        public bool DairyOrNot { get; set; }
        public int ScoreOfRation { get; set; }
        public int AmountRation { get; set; }
        public int OldAmountRation { get; set; }
        public Nullable<System.DateTime> DateUpdateAmount { get; set; }
        public string PictureRation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AmountRationInInvitation> AmountRationInInvitation { get; set; }
        public virtual FoodCategory FoodCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateRations> RateRations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RationInInvitation> RationInInvitation { get; set; }
    }
}
