//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RationInInvitation
    {
        public int CodeRationInvitation { get; set; }
        public int CodeInvitation { get; set; }
        public int CodeRation { get; set; }
        public int AmountRation { get; set; }
        public decimal PricePerServing { get; set; }
        public bool IsPerformed { get; set; }
    
        public virtual Invitations Invitations { get; set; }
        public virtual Rations Rations { get; set; }
    }
}
